/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package page;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import com.mysql.jdbc.Statement;
import java.sql.SQLException;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import modul.koneksi;

/**
 *
 * @author BYTECOM
 */
public class daftar_proyek_ui extends javax.swing.JFrame {

        /**
         * Creates new form daftar_proyek_ui
         */
        public daftar_proyek_ui() {
                initComponents();
                loadData();
                loadTable();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTable2 = new javax.swing.JTable();
                jScrollPane3 = new javax.swing.JScrollPane();
                jTable3 = new javax.swing.JTable();
                jScrollPane4 = new javax.swing.JScrollPane();
                jTable4 = new javax.swing.JTable();
                jPanel1 = new javax.swing.JPanel();
                btnEdit = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                btnDell = new javax.swing.JButton();
                jid = new javax.swing.JLabel();
                btnClear = new javax.swing.JButton();
                jnama_proyek = new javax.swing.JLabel();
                btnExit = new javax.swing.JButton();
                jlokasi = new javax.swing.JLabel();
                jpic = new javax.swing.JLabel();
                jstatus = new javax.swing.JLabel();
                comboStatus = new javax.swing.JComboBox<>();
                textId = new javax.swing.JTextField();
                textNamaProyek = new javax.swing.JTextField();
                textLokasi = new javax.swing.JTextField();
                btnSave = new javax.swing.JButton();
                jScrollPane5 = new javax.swing.JScrollPane();
                tableProject = new javax.swing.JTable();
                comboPic = new javax.swing.JComboBox<>();
                btnRefresh = new javax.swing.JButton();

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Title 1", "Title 2", "Title 3", "Title 4"
                                }));
                jScrollPane1.setViewportView(jTable1);

                jTable2.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Title 1", "Title 2", "Title 3", "Title 4"
                                }));
                jScrollPane2.setViewportView(jTable2);

                jTable3.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null }
                                },
                                new String[] {
                                                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
                                }));
                jScrollPane3.setViewportView(jTable3);

                jTable4.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Title 1", "Title 2", "Title 3", "Title 4"
                                }));
                jScrollPane4.setViewportView(jTable4);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(51, 51, 51));
                setForeground(new java.awt.Color(51, 51, 51));

                jPanel1.setBackground(new java.awt.Color(51, 51, 51));

                btnEdit.setBackground(new java.awt.Color(0, 204, 204));
                btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnEdit.setForeground(new java.awt.Color(255, 255, 255));
                btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/edit.png"))); // NOI18N
                btnEdit.setText("Edit");
                btnEdit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEditActionPerformed(evt);
                        }
                });

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Daftar Proyek");

                btnDell.setBackground(new java.awt.Color(0, 204, 204));
                btnDell.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnDell.setForeground(new java.awt.Color(255, 255, 255));
                btnDell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/delete.png"))); // NOI18N
                btnDell.setText("Delete");
                btnDell.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDellActionPerformed(evt);
                        }
                });

                jid.setBackground(new java.awt.Color(255, 255, 255));
                jid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jid.setForeground(new java.awt.Color(255, 255, 255));
                jid.setText("ID                     :");

                btnClear.setBackground(new java.awt.Color(0, 204, 204));
                btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnClear.setForeground(new java.awt.Color(255, 255, 255));
                btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/eraser.png"))); // NOI18N
                btnClear.setText("Clear");
                btnClear.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnClearActionPerformed(evt);
                        }
                });

                jnama_proyek.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jnama_proyek.setForeground(new java.awt.Color(255, 255, 255));
                jnama_proyek.setText("Nama Proyek :");

                btnExit.setBackground(new java.awt.Color(0, 204, 204));
                btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnExit.setForeground(new java.awt.Color(255, 255, 255));
                btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/logout.png"))); // NOI18N
                btnExit.setText("Exit");
                btnExit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnExitActionPerformed(evt);
                        }
                });

                jlokasi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jlokasi.setForeground(new java.awt.Color(255, 255, 255));
                jlokasi.setText("Lokasi              :");

                jpic.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jpic.setForeground(new java.awt.Color(255, 255, 255));
                jpic.setText("PIC                   :");

                jstatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jstatus.setForeground(new java.awt.Color(255, 255, 255));
                jstatus.setText("Status              :");

                comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                comboStatus.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                comboStatusActionPerformed(evt);
                        }
                });

                btnSave.setBackground(new java.awt.Color(0, 204, 204));
                btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnSave.setForeground(new java.awt.Color(255, 255, 255));
                btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/floppy-disk.png"))); // NOI18N
                btnSave.setText("Save");
                btnSave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnSave.setIconTextGap(10);
                btnSave.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSaveActionPerformed(evt);
                        }
                });

                tableProject.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null }
                                },
                                new String[] {
                                                "", "", "", "", ""
                                }));
                tableProject.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tableProjectMouseClicked(evt);
                        }
                });
                jScrollPane5.setViewportView(tableProject);

                comboPic.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                comboPic.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                comboPicActionPerformed(evt);
                        }
                });

                btnRefresh.setBackground(new java.awt.Color(0, 204, 204));
                btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
                btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/refresh.png"))); // NOI18N
                btnRefresh.setText("Refresh");
                btnRefresh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnRefresh.setIconTextGap(10);
                btnRefresh.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRefreshActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(48, 48, 48)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(btnSave)
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(btnEdit,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                87,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(btnDell,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                93,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(btnClear,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                87,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                16,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(btnExit,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                87,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                                false)
                                                                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                                                                                .addComponent(jnama_proyek)
                                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                                .addComponent(textNamaProyek))
                                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                .addComponent(jid)
                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                .addComponent(textId,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                127,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                                                                                .addComponent(jlokasi)
                                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                                .addComponent(textLokasi,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                126,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                .addComponent(jpic)
                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                .addComponent(comboPic,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                126,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                .addComponent(jstatus)
                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                .addComponent(comboStatus,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                126,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                                                                .addGap(54, 54, 54))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                .addComponent(jLabel1)
                                                                                                .addGap(81, 81, 81)
                                                                                                .addComponent(btnRefresh)
                                                                                                .addGap(36, 36, 36))))
                                                .addComponent(jScrollPane5));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(22, 22, 22)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(btnRefresh,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                43,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(49, 49, 49)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jid)
                                                                                .addComponent(textId,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jpic)
                                                                                .addComponent(comboPic,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jnama_proyek)
                                                                                .addComponent(jstatus)
                                                                                .addComponent(textNamaProyek,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(comboStatus,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(20, 20, 20)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jlokasi)
                                                                                .addComponent(textLokasi,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(50, 50, 50)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnSave)
                                                                                .addComponent(btnEdit,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                26,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnDell,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                26,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnClear,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                26,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnExit,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                26,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, Short.MAX_VALUE)
                                                                .addComponent(jScrollPane5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                127,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(217, 217, 217)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditActionPerformed
                // TODO add your handling code here:
                String id = textId.getText();
                String nama_proyek = textNamaProyek.getText();
                String lokasi = textLokasi.getText();
                String pic = comboPic.getSelectedItem().toString();
                String status = comboStatus.getSelectedItem().toString();
                String sql = "update master_project set Nama_Project='" + nama_proyek + "',Lokasi='" + lokasi
                                + "',PIC='" + pic + "',Status='" + status + "' where ID='" + id + "'";
                try {
                        java.sql.Connection con = koneksi.getKoneksi();
                        Statement stat = (Statement) con.createStatement();
                        stat.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                        loadTable();
                        con.close();
                } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Data gagal diubah");
                }
        }// GEN-LAST:event_btnEditActionPerformed

        private void btnDellActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDellActionPerformed
                // TODO add your handling code here:
                int row = tableProject.getSelectedRow();
                String id = tableProject.getValueAt(row, 0).toString();
                String nama_proyek = tableProject.getValueAt(row, 1).toString();
                String lokasi = tableProject.getValueAt(row, 2).toString();
                String status = tableProject.getValueAt(row, 3).toString();
                String pic = tableProject.getValueAt(row, 4).toString();
                String sql = "delete from master_project where ID='" + id + "'";
                try {
                        java.sql.Connection con = koneksi.getKoneksi();
                        Statement stat = (Statement) con.createStatement();
                        stat.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                        // showData();
                        loadTable();
                        textId.setText("");
                        textNamaProyek.setText("");
                        textLokasi.setText("");
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
                }
        }// GEN-LAST:event_btnDellActionPerformed

        private void tableProjectMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tableProjectMouseClicked
                // TODO add your handling code here:
                int row = tableProject.getSelectedRow();
                textId.setText(tableProject.getValueAt(row, 0).toString());
                textNamaProyek.setText(tableProject.getValueAt(row, 1).toString());
                textLokasi.setText(tableProject.getValueAt(row, 2).toString());
                comboPic.setSelectedItem(tableProject.getValueAt(row, 3).toString());
                comboStatus.setSelectedItem(tableProject.getValueAt(row, 4).toString());

        }// GEN-LAST:event_tableProjectMouseClicked

        private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnClearActionPerformed
                // TODO add your handling code here:
                textId.setText("");
                textNamaProyek.setText("");
                textLokasi.setText("");

        }// GEN-LAST:event_btnClearActionPerformed

        private void comboPicActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboPicActionPerformed
                // TODO add your handling code here:

        }// GEN-LAST:event_comboPicActionPerformed

        private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboStatusActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_comboStatusActionPerformed

        private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed
                // TODO add your handling code here:
                String namaProyek = textNamaProyek.getText();
                String lokasi = textLokasi.getText();
                String pic = comboPic.getSelectedItem().toString();
                String status = comboStatus.getSelectedItem().toString();

                if (textNamaProyek.getText().equals("") || textLokasi.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Data Belum Lengkap");
                } else {
                        // get date
                        String date = java.time.LocalDate.now().toString();
                        String dt = date.replaceAll("-", "");
                        System.out.println(dt);
                        String idProyek;
                        // get 4 first string from namaProyek
                        if (namaProyek.length() > 4) {
                                String namaProyek1 = namaProyek.substring(0, 4);
                                System.out.println(namaProyek1);
                                idProyek = dt + namaProyek1;
                                System.out.println(idProyek);
                                textId.setText(idProyek);
                        } else {
                                idProyek = dt + namaProyek;
                                System.out.println(idProyek);
                                textId.setText(idProyek);
                        }
                        // save to database
                        PreparedStatement p;
                        try {

                                java.sql.Connection con = koneksi.getKoneksi();
                                String cek = "SELECT * FROM master_project WHERE ID = '" + idProyek + "'";
                                Statement st = (Statement) con.createStatement();
                                ResultSet rs = (ResultSet) st.executeQuery(cek);
                                if (rs.next()) {
                                        JOptionPane.showMessageDialog(null, "ID Proyek sudah ada");
                                } else {
                                        String sql = "INSERT INTO master_project (ID, Nama_Project, Lokasi, PIC, Status) VALUES (?,?,?,?,?)";
                                        // java.sql.PreparedStatement statement = (PreparedStatement)
                                        // con.prepareStatement(sql);
                                        p = (PreparedStatement) con.prepareStatement(sql);
                                        p.setString(1, textId.getText());
                                        p.setString(2, namaProyek);
                                        p.setString(3, lokasi);
                                        p.setString(4, pic);
                                        p.setString(5, status);
                                        p.execute();
                                        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                                        // showTable();
                                        loadTable();
                                }

                        } catch (SQLException e) {
                                JOptionPane.showMessageDialog(null, "Data gagal disimpan");
                        }
                }

        }// GEN-LAST:event_btnSaveActionPerformed

        private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshActionPerformed
                // TODO add your handling code here:
                loadData();
                loadTable();

        }// GEN-LAST:event_btnRefreshActionPerformed

        private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExitActionPerformed
                // TODO add your handling code here:
                // close this page
                this.dispose();
        }// GEN-LAST:event_btnExitActionPerformed

        private void loadData() {
                DefaultComboBoxModel comboBoxTeknisi = new DefaultComboBoxModel();
                DefaultComboBoxModel comboBoxStatus = new DefaultComboBoxModel();

                comboBoxStatus.addElement("On Progress");
                comboBoxStatus.addElement("Selesai");
                comboStatus.setModel(comboBoxStatus);

                textId.setEditable(false);

                try {
                        java.sql.Connection con = koneksi.getKoneksi();
                        Statement stmt = (Statement) con.createStatement();
                        String sql = "SELECT Nama_Teknisi FROM teknisi";
                        ResultSet rs = (ResultSet) stmt.executeQuery(sql);
                        while (rs.next()) {
                                comboBoxTeknisi.addElement(rs.getString("Nama_Teknisi"));
                        }
                        comboPic.setModel(comboBoxTeknisi);
                        con.close();
                } catch (SQLException e) {
                        System.out.println("Error : " + e.getMessage());
                }
        }

        private void loadTable() {
                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("ID");
                model.addColumn("Nama Proyek");
                model.addColumn("Lokasi");
                model.addColumn("PIC");
                model.addColumn("Status");

                try {
                        java.sql.Connection con = koneksi.getKoneksi();
                        Statement stmt = (Statement) con.createStatement();
                        String sql = "SELECT * FROM master_project";
                        ResultSet rs = (ResultSet) stmt.executeQuery(sql);
                        while (rs.next()) {
                                model.addRow(new Object[] { rs.getString("ID"), rs.getString("Nama_Project"),
                                                rs.getString("Lokasi"), rs.getString("PIC"), rs.getString("Status") });
                        }
                        tableProject.setModel(model);
                        con.close();
                } catch (SQLException e) {
                        System.out.println("Error : " + e.getMessage());
                }

        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(daftar_proyek_ui.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(daftar_proyek_ui.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(daftar_proyek_ui.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(daftar_proyek_ui.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new daftar_proyek_ui().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnClear;
        private javax.swing.JButton btnDell;
        private javax.swing.JButton btnEdit;
        private javax.swing.JButton btnExit;
        private javax.swing.JButton btnRefresh;
        private javax.swing.JButton btnSave;
        private javax.swing.JComboBox<String> comboPic;
        private javax.swing.JComboBox<String> comboStatus;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JScrollPane jScrollPane5;
        private javax.swing.JTable jTable1;
        private javax.swing.JTable jTable2;
        private javax.swing.JTable jTable3;
        private javax.swing.JTable jTable4;
        private javax.swing.JLabel jid;
        private javax.swing.JLabel jlokasi;
        private javax.swing.JLabel jnama_proyek;
        private javax.swing.JLabel jpic;
        private javax.swing.JLabel jstatus;
        private javax.swing.JTable tableProject;
        private javax.swing.JTextField textId;
        private javax.swing.JTextField textLokasi;
        private javax.swing.JTextField textNamaProyek;
        // End of variables declaration//GEN-END:variables
}
