/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package page;

import com.mysql.jdbc.ResultSet;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;

//import itext docment
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import modul.koneksi;
import modul.userSession;

/**
 *
 * @author BYTECOM
 */
public class halaman_report_ui extends javax.swing.JFrame {

    /**
     * Creates new form daftar_proyek_ui
     */
    public halaman_report_ui() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jid = new javax.swing.JLabel();
        jnama_proyek = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jlokasi = new javax.swing.JLabel();
        jlokasi1 = new javax.swing.JLabel();
        jlokasi2 = new javax.swing.JLabel();
        comboTimeline = new javax.swing.JComboBox<>();
        comboReport = new javax.swing.JComboBox<>();
        btnUnduh1 = new javax.swing.JButton();
        btnUnduh2 = new javax.swing.JButton();
        btnUnduh3 = new javax.swing.JButton();
        btnUnduh4 = new javax.swing.JButton();
        btnUnduh5 = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
                }));
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane4.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Halaman Report");

        jid.setBackground(new java.awt.Color(255, 255, 255));
        jid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jid.setForeground(new java.awt.Color(255, 255, 255));
        jid.setText("Daftar Proyek      :");

        jnama_proyek.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jnama_proyek.setForeground(new java.awt.Color(255, 255, 255));
        jnama_proyek.setText("Timeline                :");

        btnExit.setBackground(new java.awt.Color(0, 204, 204));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/logout.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jlokasi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlokasi.setForeground(new java.awt.Color(255, 255, 255));
        jlokasi.setText("Report Proyek     :");

        jlokasi1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlokasi1.setForeground(new java.awt.Color(255, 255, 255));
        jlokasi1.setText("Maintance             :");

        jlokasi2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlokasi2.setForeground(new java.awt.Color(255, 255, 255));
        jlokasi2.setText("QA                          :");

        comboTimeline.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTimeline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTimelineActionPerformed(evt);
            }
        });

        comboReport.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboReportActionPerformed(evt);
            }
        });

        btnUnduh1.setBackground(new java.awt.Color(0, 204, 204));
        btnUnduh1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUnduh1.setForeground(new java.awt.Color(255, 255, 255));
        btnUnduh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/download.png"))); // NOI18N
        btnUnduh1.setText("Unduh");
        btnUnduh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnduh1ActionPerformed(evt);
            }
        });

        btnUnduh2.setBackground(new java.awt.Color(0, 204, 204));
        btnUnduh2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUnduh2.setForeground(new java.awt.Color(255, 255, 255));
        btnUnduh2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/download.png"))); // NOI18N
        btnUnduh2.setText("Unduh");
        btnUnduh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnduh2ActionPerformed(evt);
            }
        });

        btnUnduh3.setBackground(new java.awt.Color(0, 204, 204));
        btnUnduh3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUnduh3.setForeground(new java.awt.Color(255, 255, 255));
        btnUnduh3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/download.png"))); // NOI18N
        btnUnduh3.setText("Unduh");
        btnUnduh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnduh3ActionPerformed(evt);
            }
        });

        btnUnduh4.setBackground(new java.awt.Color(0, 204, 204));
        btnUnduh4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUnduh4.setForeground(new java.awt.Color(255, 255, 255));
        btnUnduh4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/download.png"))); // NOI18N
        btnUnduh4.setText("Unduh");
        btnUnduh4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnduh4ActionPerformed(evt);
            }
        });

        btnUnduh5.setBackground(new java.awt.Color(0, 204, 204));
        btnUnduh5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUnduh5.setForeground(new java.awt.Color(255, 255, 255));
        btnUnduh5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/download.png"))); // NOI18N
        btnUnduh5.setText("Unduh");
        btnUnduh5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnduh5ActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(0, 204, 204));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/refresh_small.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jid)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jnama_proyek)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(comboTimeline,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 127,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jlokasi2))
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnUnduh4)
                                                        .addComponent(btnUnduh5)
                                                        .addComponent(btnUnduh3)
                                                        .addComponent(btnUnduh2)
                                                        .addComponent(btnUnduh1)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jlokasi)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(comboReport, javax.swing.GroupLayout.PREFERRED_SIZE, 127,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jlokasi1))
                                .addContainerGap(25, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(111, 111, 111)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jid)
                                        .addComponent(btnUnduh1, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jnama_proyek)
                                        .addComponent(comboTimeline, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUnduh2, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlokasi)
                                        .addComponent(comboReport, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUnduh3, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlokasi1)
                                        .addComponent(btnUnduh4, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlokasi2)
                                        .addComponent(btnUnduh5, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboDaftarProyekActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboDaftarProyekActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_comboDaftarProyekActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }// GEN-LAST:event_btnExitActionPerformed

    private void comboTimelineActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboTimelineActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_comboTimelineActionPerformed

    private void comboReportActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboReportActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_comboReportActionPerformed

    private void comboMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboMaintenanceActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_comboMaintenanceActionPerformed

    private void comboBastActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboBastActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_comboBastActionPerformed

    private void btnUnduh1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUnduh1ActionPerformed
        // TODO add your handling code here:
        // daftar proyek
        String date = java.time.LocalDate.now().toString();
        String fileName = "D:\\" + date + " - Daftar Proyek.pdf";

        // create document object
        try {
            Document document = new Document() {
            };
            PdfWriter.getInstance((com.itextpdf.text.Document) document, new FileOutputStream(fileName));
            document.open();
            Paragraph p = new Paragraph("Daftar Proyek");
            p.setAlignment(Element.ALIGN_CENTER);
            document.add(p);
            // ad null paragraf
            document.add(new Paragraph("\n"));

            // pull data from db
            String sql = "SELECT * FROM master_project";

            try {
                java.sql.Connection conn = (Connection) koneksi.getKoneksi();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                // create table
                PdfPTable table = new PdfPTable(res.getMetaData().getColumnCount());
                for (int i = 1; i <= res.getMetaData().getColumnCount(); i++) {
                    System.out.println(res.getMetaData().getColumnName(i));
                    table.addCell(res.getMetaData().getColumnName(i));
                }

                while (res.next()) {
                    for (int i = 1; i <= res.getMetaData().getColumnCount(); i++) {
                        table.addCell(res.getString(i));
                    }
                }
                document.add(table);
                conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "File berhasil diunduh");

    }// GEN-LAST:event_btnUnduh1ActionPerformed

    private void btnUnduh2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUnduh2ActionPerformed
        // TODO add your handling code here:
        // timeline
        String tm = comboTimeline.getSelectedItem().toString();
        String date = java.time.LocalDate.now().toString();
        String fileName = "D:\\" + date + " - Timeline - " + tm + ".pdf";

        // create document object
        try {
            Document document = new Document() {
            };
            PdfWriter.getInstance((com.itextpdf.text.Document) document, new FileOutputStream(fileName));
            document.open();
            Paragraph p = new Paragraph("Timeline - " + tm);
            p.setAlignment(Element.ALIGN_CENTER);
            document.add(p);
            // ad null paragraf
            document.add(new Paragraph("\n"));
            // pull data from db
            String sql = "SELECT * FROM timeline_project WHERE Nama_Project = '" + tm + "'";
            try {
                java.sql.Connection conn = (Connection) koneksi.getKoneksi();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                // create table
                PdfPTable table = new PdfPTable(res.getMetaData().getColumnCount());
                for (int i = 1; i <= res.getMetaData().getColumnCount(); i++) {
                    System.out.println(res.getMetaData().getColumnName(i));
                    table.addCell(res.getMetaData().getColumnName(i));
                }

                while (res.next()) {
                    for (int i = 1; i <= res.getMetaData().getColumnCount(); i++) {
                        table.addCell(res.getString(i));
                    }
                }
                document.add(table);
                conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "File berhasil diunduh");
    }// GEN-LAST:event_btnUnduh2ActionPerformed

    private void btnUnduh3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUnduh3ActionPerformed
        // TODO add your handling code here:
        // report
        String rp = comboReport.getSelectedItem().toString();
        String date = java.time.LocalDate.now().toString();
        String fileName = "D:\\" + date + " - Report - " + rp + ".pdf";

        // create document object
        try {
            Document document = new Document() {
            };
            PdfWriter.getInstance((com.itextpdf.text.Document) document, new FileOutputStream(fileName));
            document.open();
            Paragraph p = new Paragraph("Report - " + rp);
            p.setAlignment(Element.ALIGN_CENTER);
            document.add(p);
            // ad null paragraf
            document.add(new Paragraph("\n"));
            // pull data from db
            String sql = "SELECT * FROM report_project WHERE Nama_Project = '" + rp + "'";
            try {
                java.sql.Connection conn = (Connection) koneksi.getKoneksi();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                // create table
                PdfPTable table = new PdfPTable(res.getMetaData().getColumnCount());
                for (int i = 1; i <= res.getMetaData().getColumnCount(); i++) {
                    System.out.println(res.getMetaData().getColumnName(i));
                    table.addCell(res.getMetaData().getColumnName(i));
                }

                while (res.next()) {
                    for (int i = 1; i <= res.getMetaData().getColumnCount(); i++) {
                        if (i == 7) {
                            byte[] img = res.getBytes(i);
                            com.itextpdf.text.Image image = com.itextpdf.text.Image.getInstance(img);
                            table.addCell(image);
                        } else {
                            table.addCell(res.getString(i));
                        }
                        // table.addCell(res.getString(i));
                    }
                }
                document.add(table);
                conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "File berhasil diunduh");
    }// GEN-LAST:event_btnUnduh3ActionPerformed

    private void btnUnduh4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUnduh4ActionPerformed
        // TODO add your handling code here:
        // maintance
        String date = java.time.LocalDate.now().toString();
        String fileName = "D:\\" + date + " - Maintenance.pdf";
        // create document object
        try {
            Document document = new Document() {
            };
            PdfWriter.getInstance((com.itextpdf.text.Document) document, new FileOutputStream(fileName));
            document.open();
            Paragraph p = new Paragraph("Maintenance");
            p.setAlignment(Element.ALIGN_CENTER);
            document.add(p);
            // ad null paragraf
            document.add(new Paragraph("\n"));
            // pull data from db
            String sql = "SELECT * FROM maintenance";
            try {
                java.sql.Connection conn = (Connection) koneksi.getKoneksi();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                // create table
                PdfPTable table = new PdfPTable(res.getMetaData().getColumnCount());
                for (int i = 1; i <= res.getMetaData().getColumnCount(); i++) {
                    System.out.println(res.getMetaData().getColumnName(i));
                    table.addCell(res.getMetaData().getColumnName(i));
                }

                while (res.next()) {
                    for (int i = 1; i <= res.getMetaData().getColumnCount(); i++) {
                        table.addCell(res.getString(i));
                    }
                }
                document.add(table);
                conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "File berhasil diunduh");
    }// GEN-LAST:event_btnUnduh4ActionPerformed

    private void btnUnduh5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUnduh5ActionPerformed
        // TODO add your handling code here:
        // report
        String date = java.time.LocalDate.now().toString();
        String fileName = "D:\\" + date + " - QA.pdf";
        // create document object
        try {
            Document document = new Document() {
            };
            PdfWriter.getInstance((com.itextpdf.text.Document) document, new FileOutputStream(fileName));
            document.open();
            Paragraph p = new Paragraph("QA");
            p.setAlignment(Element.ALIGN_CENTER);
            document.add(p);
            // ad null paragraf
            document.add(new Paragraph("\n"));
            // pull data from db
            String sql = "SELECT * FROM qa";
            try {
                java.sql.Connection conn = (Connection) koneksi.getKoneksi();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                // create table
                PdfPTable table = new PdfPTable(res.getMetaData().getColumnCount());
                for (int i = 1; i <= res.getMetaData().getColumnCount(); i++) {
                    System.out.println(res.getMetaData().getColumnName(i));
                    table.addCell(res.getMetaData().getColumnName(i));
                }

                while (res.next()) {
                    for (int i = 1; i <= res.getMetaData().getColumnCount(); i++) {
                        table.addCell(res.getString(i));
                    }
                }
                document.add(table);
                conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "File berhasil diunduh");

    }// GEN-LAST:event_btnUnduh5ActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadData();
    }// GEN-LAST:event_btnRefreshActionPerformed

    private void loadData() {
        DefaultComboBoxModel model1 = new DefaultComboBoxModel();
        DefaultComboBoxModel model2 = new DefaultComboBoxModel();
        DefaultComboBoxModel model3 = new DefaultComboBoxModel();
        DefaultComboBoxModel model4 = new DefaultComboBoxModel();
        DefaultComboBoxModel model5 = new DefaultComboBoxModel();

        model1.addElement("---Daftar Proyek---");
        model2.addElement("---Timeline---");
        model3.addElement("---Report---");
        model4.addElement("---Maintenance---");
        model5.addElement("---BAST---");

        String sql1 = "select Nama_Project from master_project"; // daftar proyek
        String sql2 = "select Nama_Project from master_project where Status LIKE '%progress%'"; // timeline
        String sql3 = "select Nama_Project from master_project where Status LIKE '%progress%'"; // report
        String sql4 = "select Nama_Project from master_project where Status LIKE '%selesai%'"; // maintenance
        String sql5 = "select Nama_Project from master_project where Status LIKE '%progress%'"; // bast

        try {
            java.sql.Connection con;
            PreparedStatement p;
            con = (Connection) koneksi.getKoneksi();
            p = (PreparedStatement) con.prepareStatement(sql1);
            ResultSet rs = (ResultSet) p.executeQuery();
            while (rs.next()) {
                model1.addElement(rs.getString("Nama_Project"));
            }

            p = (PreparedStatement) con.prepareStatement(sql2);
            rs = (ResultSet) p.executeQuery();
            while (rs.next()) {
                model2.addElement(rs.getString("Nama_Project"));
            }

            p = (PreparedStatement) con.prepareStatement(sql3);
            rs = (ResultSet) p.executeQuery();
            while (rs.next()) {
                model3.addElement(rs.getString("Nama_Project"));
            }

            p = (PreparedStatement) con.prepareStatement(sql4);
            rs = (ResultSet) p.executeQuery();
            while (rs.next()) {
                model4.addElement(rs.getString("Nama_Project"));
            }

            p = (PreparedStatement) con.prepareStatement(sql5);
            rs = (ResultSet) p.executeQuery();
            while (rs.next()) {
                model5.addElement(rs.getString("Nama_Project"));
            }

            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        // comboDaftarProyek.setModel(model1);
        comboTimeline.setModel(model2);
        comboReport.setModel(model3);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halaman_report_ui.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halaman_report_ui.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halaman_report_ui.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halaman_report_ui.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halaman_report_ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUnduh1;
    private javax.swing.JButton btnUnduh2;
    private javax.swing.JButton btnUnduh3;
    private javax.swing.JButton btnUnduh4;
    private javax.swing.JButton btnUnduh5;
    private javax.swing.JComboBox<String> comboReport;
    private javax.swing.JComboBox<String> comboTimeline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel jid;
    private javax.swing.JLabel jlokasi;
    private javax.swing.JLabel jlokasi1;
    private javax.swing.JLabel jlokasi2;
    private javax.swing.JLabel jnama_proyek;
    // End of variables declaration//GEN-END:variables
}
