/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package page;

import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import com.mysql.jdbc.Statement;

import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modul.koneksi;
import modul.userSession;

/**
 *
 * @author BYTECOM
 */
public class maintenance_ui extends javax.swing.JFrame {

    String ulv = userSession.getUserLevel();

        /**
         * Creates new form daftar_proyek_ui
         */
        public maintenance_ui() {
                initComponents();
                loadData();
                loadTable();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDell = new javax.swing.JButton();
        jid = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jnama_proyek = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jpic = new javax.swing.JLabel();
        comboPic = new javax.swing.JComboBox<>();
        comboNamaProyek = new javax.swing.JComboBox<>();
        textNoTiket = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableMtc = new javax.swing.JTable();
        jproblem = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        textAction = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        textProblem = new javax.swing.JTextArea();
        jaction = new javax.swing.JLabel();
        dateMtc = new com.toedter.calendar.JDateChooser();
        jpic1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btnEdit.setBackground(new java.awt.Color(0, 204, 204));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Maintance");

        btnDell.setBackground(new java.awt.Color(0, 204, 204));
        btnDell.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDell.setForeground(new java.awt.Color(255, 255, 255));
        btnDell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/delete.png"))); // NOI18N
        btnDell.setText("Delete");
        btnDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDellActionPerformed(evt);
            }
        });

        jid.setBackground(new java.awt.Color(255, 255, 255));
        jid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jid.setForeground(new java.awt.Color(255, 255, 255));
        jid.setText("Nomer Tiket  :");

        btnClear.setBackground(new java.awt.Color(0, 204, 204));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/eraser.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jnama_proyek.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jnama_proyek.setForeground(new java.awt.Color(255, 255, 255));
        jnama_proyek.setText("Nama Proyek :");

        btnExit.setBackground(new java.awt.Color(0, 204, 204));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/logout.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(0, 204, 204));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRefresh.setIconTextGap(10);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jpic.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jpic.setForeground(new java.awt.Color(255, 255, 255));
        jpic.setText("PIC                   :");

        comboPic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPicActionPerformed(evt);
            }
        });

        comboNamaProyek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSave.setBackground(new java.awt.Color(0, 204, 204));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_icon/floppy-disk.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSave.setIconTextGap(10);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tableMtc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        tableMtc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMtcMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tableMtc);

        jproblem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jproblem.setForeground(new java.awt.Color(255, 255, 255));
        jproblem.setText("Action             :");

        textAction.setColumns(20);
        textAction.setRows(5);
        jScrollPane6.setViewportView(textAction);

        textProblem.setColumns(20);
        textProblem.setRows(5);
        jScrollPane7.setViewportView(textProblem);

        jaction.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jaction.setForeground(new java.awt.Color(255, 255, 255));
        jaction.setText("Problem          :");

        jpic1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jpic1.setForeground(new java.awt.Color(255, 255, 255));
        jpic1.setText("Tanggal           :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jnama_proyek)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboNamaProyek, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jid)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textNoTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(btnSave)
                                    .addGap(29, 29, 29)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jaction)
                                .addGap(137, 137, 137)))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jproblem)
                        .addComponent(jpic))
                    .addComponent(jpic1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dateMtc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboPic, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btnDell, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(112, 112, 112)
                        .addComponent(btnRefresh)
                        .addGap(34, 34, 34)))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnRefresh))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jid)
                    .addComponent(textNoTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpic)
                    .addComponent(comboPic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jnama_proyek)
                        .addComponent(comboNamaProyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpic1))
                    .addComponent(dateMtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jaction)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSave)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDell, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jproblem)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void comboPicActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboPicActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_comboPicActionPerformed

        private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshActionPerformed
                // TODO add your handling code here:
                loadData();
                loadTable();
        }// GEN-LAST:event_btnRefreshActionPerformed

        private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExitActionPerformed
                // TODO add your handling code here:
                this.dispose();
        }// GEN-LAST:event_btnExitActionPerformed

        private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed
                // TODO add your handling code here:
                java.sql.Connection con;
                PreparedStatement p;
                String np = comboNamaProyek.getSelectedItem().toString();
                String pic = comboPic.getSelectedItem().toString();
                String action = textAction.getText();
                String problem = textProblem.getText();
                Date mtc = new java.sql.Date(dateMtc.getDate().getTime());

                if (np.equals("--Pilih Nama Proyek--") || pic.equals("--Pilih PIC--") || action.equals("")
                                || problem.equals("")
                                || mtc.equals(null)) {
                        JOptionPane.showMessageDialog(null, "Data tidak boleh kosong");
                } else {
                        try {
                                // get date
                                String date = java.time.LocalDate.now().toString();
                                String dt = date.replaceAll("-", "/");
                                System.out.println(dt);

                                // get time
                                String time = java.time.LocalTime.now().toString();
                                LocalTime tm = LocalTime.parse(time);
                                int sc = tm.getSecond();

                                // get 4 first string from namaProyek
                                String noTiket;
                                if (np.length() > 4) {
                                        String np1 = np.substring(0, 4);
                                        System.out.println(np1);
                                        noTiket = "MTC/" + dt + "/" + np1 + "/" + sc;
                                        System.out.println(noTiket);
                                        textNoTiket.setText(noTiket);
                                } else {
                                        noTiket = "MTC/" + dt + "/" + np + "/" + sc;
                                        System.out.println(noTiket);
                                        textNoTiket.setText(noTiket);
                                }

                                con = koneksi.getKoneksi();
                                p = (PreparedStatement) con
                                                .prepareStatement("insert into maintenance values(?,?,?,?,?,?)");
                                p.setString(1, textNoTiket.getText());
                                p.setString(2, np);
                                p.setString(5, pic);
                                p.setString(6, action);
                                p.setString(4, problem);
                                p.setDate(3, (java.sql.Date) mtc);
                                p.executeUpdate();
                                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                                loadData();
                                loadTable();
                        } catch (Exception ex) {
                                JOptionPane.showMessageDialog(null, "Data gagal disimpan");
                        }
                }
        }// GEN-LAST:event_btnSaveActionPerformed

        private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditActionPerformed
                // TODO add your handling code here:
                int row = tableMtc.getSelectedRow();
                String problem = tableMtc.getValueAt(row, 3).toString();
                String action = tableMtc.getValueAt(row, 5).toString();
                String tgl = tableMtc.getValueAt(row, 2).toString();
                String pic = tableMtc.getValueAt(row, 4).toString();

                String newproblem = textProblem.getText();
                String newaction = textAction.getText();
                String newtgl = dateMtc.getDate().toString();
                String newpic = comboPic.getSelectedItem().toString();

                Date mtc = new java.sql.Date(dateMtc.getDate().getTime());
                if (row == -1) {
                        JOptionPane.showMessageDialog(null, "Pilih data yang akan diubah");
                } else if (newproblem.equals(problem) && newaction.equals(action) && newtgl.equals(tgl)
                                && newpic.equals(pic)) {
                        JOptionPane.showMessageDialog(null, "Data tidak berubah");
                } else {
                        try {
                                java.sql.Connection con;
                                PreparedStatement p;
                                con = koneksi.getKoneksi();
                                p = (PreparedStatement) con.prepareStatement(
                                                "update maintenance set Problem=?, Action=?, Tanggal=?, PIC=? where No_Ticket=?");
                                p.setString(1, newproblem);
                                p.setString(2, newaction);
                                p.setDate(3, (java.sql.Date) mtc);
                                p.setString(4, newpic);
                                p.setString(5, textNoTiket.getText());
                                p.executeUpdate();
                                JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                                loadData();
                                loadTable();
                        } catch (Exception ex) {
                                JOptionPane.showMessageDialog(null, "Data gagal diubah");
                        }
                }

        }// GEN-LAST:event_btnEditActionPerformed

        private void btnDellActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDellActionPerformed
                // TODO add your handling code here:
                int row = tableMtc.getSelectedRow();
                if (row == -1) {
                        JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus");
                } else {
                        try {
                                java.sql.Connection con;
                                PreparedStatement p;
                                con = koneksi.getKoneksi();
                                p = (PreparedStatement) con
                                                .prepareStatement("delete from maintenance where No_Ticket=?");
                                p.setString(1, textNoTiket.getText());
                                p.executeUpdate();
                                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                                loadData();
                                loadTable();
                        } catch (Exception ex) {
                                JOptionPane.showMessageDialog(null, "Data gagal dihapus");
                        }
                }
        }// GEN-LAST:event_btnDellActionPerformed

        private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnClearActionPerformed
                // TODO add your handling code here:
                textNoTiket.setText("");
                comboNamaProyek.setSelectedIndex(0);
                textProblem.setText("");
                textAction.setText("");
                comboPic.setSelectedIndex(0);
                dateMtc.setDate(null);

        }// GEN-LAST:event_btnClearActionPerformed

        private void tableMtcMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tableMtcMouseClicked
                // TODO add your handling code here:
                int row = tableMtc.getSelectedRow();
                textNoTiket.setText(tableMtc.getValueAt(row, 0).toString());
                comboNamaProyek.setSelectedItem(tableMtc.getValueAt(row, 1).toString());
                textProblem.setText(tableMtc.getValueAt(row, 3).toString());
                textAction.setText(tableMtc.getValueAt(row, 5).toString());
                comboPic.setSelectedItem(tableMtc.getValueAt(row, 4).toString());
                String date = tableMtc.getValueAt(row, 2).toString();
                try {
                        Date d = new SimpleDateFormat("yyyy-mm-dd").parse(date);
                        dateMtc.setDate(d);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error");
                }
        }// GEN-LAST:event_tableMtcMouseClicked

        private void loadData() {
                DefaultComboBoxModel model1 = new DefaultComboBoxModel();
                DefaultComboBoxModel model2 = new DefaultComboBoxModel();

                model1.addElement("--Pilih Nama Proyek--");
                model2.addElement("--Pilih PIC--");

                textNoTiket.setEditable(false);

                try {
                        java.sql.Connection con = koneksi.getKoneksi();
                        Statement stmt = (Statement) con.createStatement();
                        String sql1 = "SELECT Nama_Teknisi FROM teknisi";
                        String sql2 = "SELECT Nama_Project FROM master_project where Status LIKE '%selesai%'";
                        ResultSet rs = (ResultSet) stmt.executeQuery(sql2);
                        while (rs.next()) {
                                model1.addElement(rs.getString("Nama_Project"));
                        }
                        comboNamaProyek.setModel(model1);
                        rs = (ResultSet) stmt.executeQuery(sql1);
                        while (rs.next()) {
                                model2.addElement(rs.getString("Nama_Teknisi"));
                        }
                        comboPic.setModel(model2);
                        con.close();
                } catch (Exception e) {
                        System.out.println("Error : " + e.getMessage());
                }
        }

        private void loadTable() {
                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("No Tiket");
                model.addColumn("Nama Proyek");
                model.addColumn("Tanggal");
                model.addColumn("Problem");
                model.addColumn("PIC");
                model.addColumn("Action");

                tableMtc.setModel(model);
                try {
                        java.sql.Connection con = koneksi.getKoneksi();
                        Statement stmt = (Statement) con.createStatement();
                        String sql = "SELECT * FROM maintenance";
                        ResultSet rs = (ResultSet) stmt.executeQuery(sql);
                        while (rs.next()) {
                                model.addRow(new Object[] {
                                                rs.getString("No_Ticket"),
                                                rs.getString("Nama_Project"),
                                                rs.getString("Tanggal"),
                                                rs.getString("Problem"),
                                                rs.getString("PIC"),
                                                rs.getString("Action")
                                });
                        }
                        con.close();
                } catch (Exception e) {
                        System.out.println("Error : " + e.getMessage());
                }
        
                // String ulv = userSession.getUserLevel();
                System.out.println(ulv);
                // JOptionPane.showMessageDialog(null, "anda login sebgai " + ulv);
                switch (ulv) {
                    case "admin":
                        btnSave.setEnabled(true);
                        btnDell.setEnabled(true);
                        btnEdit.setEnabled(true);
                        break;
                    case "teknisi":
                        btnSave.setEnabled(false);
                        btnDell.setEnabled(false);
                        btnEdit.setEnabled(false);
                        break;
                    case "ceo":
                        btnSave.setEnabled(true);
                        btnDell.setEnabled(true);
                        btnEdit.setEnabled(true);
                        break;
                    default:
                        break;
                }
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(maintenance_ui.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(maintenance_ui.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(maintenance_ui.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(maintenance_ui.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new maintenance_ui().setVisible(true);
                        }
                });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDell;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboNamaProyek;
    private javax.swing.JComboBox<String> comboPic;
    private com.toedter.calendar.JDateChooser dateMtc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel jaction;
    private javax.swing.JLabel jid;
    private javax.swing.JLabel jnama_proyek;
    private javax.swing.JLabel jpic;
    private javax.swing.JLabel jpic1;
    private javax.swing.JLabel jproblem;
    private javax.swing.JTable tableMtc;
    private javax.swing.JTextArea textAction;
    private javax.swing.JTextField textNoTiket;
    private javax.swing.JTextArea textProblem;
    // End of variables declaration//GEN-END:variables
}
